[project]
name = "insight-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "czx", email = "czx@example.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.16.0",
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-core>=1.6.4",
    "langchain-openai>=1.6.6",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.12",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.4",
    "trafilatura>=2.2.0",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
insight-agent = "insight_agent:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
